before_script:
  - export LANG=en_US.UTF-8
before_install:
  - gem install cocoapods -v '0.32.1'
language: objective-c
xcode_workspace: SallyCocoa.xcworkspace
xcode_scheme: SallyCocoaTests
xcode_sdk: iphonesimulator7.1
